### ISSUE TITLE
两点功能建议

### ISSUE THREAD

**Issue by ghost** [lxfly2000/7zsfx#1]
您好！这7zsfx非常小巧好用，感谢付出！

希望继续增加功能：
1、可定义自适应运行64/32位程序，这里有模板：
      https://pan.lanzoui.com/b0f1diyeb (单文件制作工具_v7.0.1.1_x86_x64.7z by JexChan)
      https://www.lanzoui.com/i8DuOu2baud  密码:cj95
2、添加指定图标、作者、版本等。

辛苦！感谢！

**Comment by lxfly2000** [comment]
我这个只是简单封装了下7zip命令行工具的功能，没法实现你说的这些，识别32/64位可以自己写个启动器判断，修改图标、版本信息要用VS重新编译SFX模块
